// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: goddess/api/v1/self.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SelfService_Info_FullMethodName         = "/goddess.api.v1.SelfService/Info"
	SelfService_Namespaces_FullMethodName   = "/goddess.api.v1.SelfService/Namespaces"
	SelfService_ChangeEmail_FullMethodName  = "/goddess.api.v1.SelfService/ChangeEmail"
	SelfService_ChangeAvatar_FullMethodName = "/goddess.api.v1.SelfService/ChangeAvatar"
	SelfService_RefreshToken_FullMethodName = "/goddess.api.v1.SelfService/RefreshToken"
)

// SelfServiceClient is the client API for SelfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelfServiceClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*UserItem, error)
	Namespaces(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*NamespacesReply, error)
	ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailReply, error)
	ChangeAvatar(ctx context.Context, in *ChangeAvatarRequest, opts ...grpc.CallOption) (*ChangeAvatarReply, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenReply, error)
}

type selfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSelfServiceClient(cc grpc.ClientConnInterface) SelfServiceClient {
	return &selfServiceClient{cc}
}

func (c *selfServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*UserItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserItem)
	err := c.cc.Invoke(ctx, SelfService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfServiceClient) Namespaces(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*NamespacesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespacesReply)
	err := c.cc.Invoke(ctx, SelfService_Namespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfServiceClient) ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeEmailReply)
	err := c.cc.Invoke(ctx, SelfService_ChangeEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfServiceClient) ChangeAvatar(ctx context.Context, in *ChangeAvatarRequest, opts ...grpc.CallOption) (*ChangeAvatarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeAvatarReply)
	err := c.cc.Invoke(ctx, SelfService_ChangeAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenReply)
	err := c.cc.Invoke(ctx, SelfService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelfServiceServer is the server API for SelfService service.
// All implementations must embed UnimplementedSelfServiceServer
// for forward compatibility.
type SelfServiceServer interface {
	Info(context.Context, *InfoRequest) (*UserItem, error)
	Namespaces(context.Context, *InfoRequest) (*NamespacesReply, error)
	ChangeEmail(context.Context, *ChangeEmailRequest) (*ChangeEmailReply, error)
	ChangeAvatar(context.Context, *ChangeAvatarRequest) (*ChangeAvatarReply, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenReply, error)
	mustEmbedUnimplementedSelfServiceServer()
}

// UnimplementedSelfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelfServiceServer struct{}

func (UnimplementedSelfServiceServer) Info(context.Context, *InfoRequest) (*UserItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSelfServiceServer) Namespaces(context.Context, *InfoRequest) (*NamespacesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Namespaces not implemented")
}
func (UnimplementedSelfServiceServer) ChangeEmail(context.Context, *ChangeEmailRequest) (*ChangeEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (UnimplementedSelfServiceServer) ChangeAvatar(context.Context, *ChangeAvatarRequest) (*ChangeAvatarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAvatar not implemented")
}
func (UnimplementedSelfServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedSelfServiceServer) mustEmbedUnimplementedSelfServiceServer() {}
func (UnimplementedSelfServiceServer) testEmbeddedByValue()                     {}

// UnsafeSelfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelfServiceServer will
// result in compilation errors.
type UnsafeSelfServiceServer interface {
	mustEmbedUnimplementedSelfServiceServer()
}

func RegisterSelfServiceServer(s grpc.ServiceRegistrar, srv SelfServiceServer) {
	// If the following call pancis, it indicates UnimplementedSelfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelfService_ServiceDesc, srv)
}

func _SelfService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfService_Namespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfServiceServer).Namespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfService_Namespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfServiceServer).Namespaces(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfService_ChangeEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfServiceServer).ChangeEmail(ctx, req.(*ChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfService_ChangeAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfServiceServer).ChangeAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfService_ChangeAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfServiceServer).ChangeAvatar(ctx, req.(*ChangeAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SelfService_ServiceDesc is the grpc.ServiceDesc for SelfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goddess.api.v1.SelfService",
	HandlerType: (*SelfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _SelfService_Info_Handler,
		},
		{
			MethodName: "Namespaces",
			Handler:    _SelfService_Namespaces_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _SelfService_ChangeEmail_Handler,
		},
		{
			MethodName: "ChangeAvatar",
			Handler:    _SelfService_ChangeAvatar_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _SelfService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goddess/api/v1/self.proto",
}
