// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: magicbox/api/v1/member.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMemberGetMember = "/magicbox.api.v1.Member/GetMember"
const OperationMemberListMember = "/magicbox.api.v1.Member/ListMember"
const OperationMemberSelectMember = "/magicbox.api.v1.Member/SelectMember"

type MemberHTTPServer interface {
	GetMember(context.Context, *GetMemberRequest) (*MemberItem, error)
	ListMember(context.Context, *ListMemberRequest) (*ListMemberReply, error)
	SelectMember(context.Context, *SelectMemberRequest) (*SelectMemberReply, error)
}

func RegisterMemberHTTPServer(s *http.Server, srv MemberHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/members", _Member_ListMember0_HTTP_Handler(srv))
	r.GET("/v1/member/{uid}", _Member_GetMember0_HTTP_Handler(srv))
	r.GET("/v1/members/select", _Member_SelectMember0_HTTP_Handler(srv))
}

func _Member_ListMember0_HTTP_Handler(srv MemberHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMemberListMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMember(ctx, req.(*ListMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMemberReply)
		return ctx.Result(200, reply)
	}
}

func _Member_GetMember0_HTTP_Handler(srv MemberHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMemberGetMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMember(ctx, req.(*GetMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemberItem)
		return ctx.Result(200, reply)
	}
}

func _Member_SelectMember0_HTTP_Handler(srv MemberHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SelectMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMemberSelectMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SelectMember(ctx, req.(*SelectMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SelectMemberReply)
		return ctx.Result(200, reply)
	}
}

type MemberHTTPClient interface {
	GetMember(ctx context.Context, req *GetMemberRequest, opts ...http.CallOption) (rsp *MemberItem, err error)
	ListMember(ctx context.Context, req *ListMemberRequest, opts ...http.CallOption) (rsp *ListMemberReply, err error)
	SelectMember(ctx context.Context, req *SelectMemberRequest, opts ...http.CallOption) (rsp *SelectMemberReply, err error)
}

type MemberHTTPClientImpl struct {
	cc *http.Client
}

func NewMemberHTTPClient(client *http.Client) MemberHTTPClient {
	return &MemberHTTPClientImpl{client}
}

func (c *MemberHTTPClientImpl) GetMember(ctx context.Context, in *GetMemberRequest, opts ...http.CallOption) (*MemberItem, error) {
	var out MemberItem
	pattern := "/v1/member/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMemberGetMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MemberHTTPClientImpl) ListMember(ctx context.Context, in *ListMemberRequest, opts ...http.CallOption) (*ListMemberReply, error) {
	var out ListMemberReply
	pattern := "/v1/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMemberListMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MemberHTTPClientImpl) SelectMember(ctx context.Context, in *SelectMemberRequest, opts ...http.CallOption) (*SelectMemberReply, error) {
	var out SelectMemberReply
	pattern := "/v1/members/select"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMemberSelectMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
